export default [
  {
    id: 1,
    date: new Date(2020, 1, 26),
    title: 'Starbucks',
    amount: '26,00',
    type: 'debit',
    category: 'food',
  },
  {
    id: 3,
    date: new Date(2020, 1, 26),
    title: 'Maracujá',
    amount: '48,00',
    type: 'debit',
    category: 'food',
  },
  {
    id: 4,
    date: new Date(2020, 1, 26),
    title: 'Uber',
    amount: '13,45',
    type: 'debit',
    category: 'transport',
  },
  {
    id: 5,
    date: new Date(2020, 1, 26),
    title: 'Poker Night',
    amount: '130,45',
    type: 'credit',
    category: 'fun',
  },
  {
    id: 6,
    date: new Date(2020, 1, 26),
    title: 'Starbucks',
    amount: '26,00',
    type: 'debit',
    category: 'food',
  },
  {
    id: 7,
    date: new Date(2020, 1, 26),
    title: 'Maracujá',
    amount: '48,00',
    type: 'debit',
    category: 'food',
  },
  {
    id: 8,
    date: new Date(2020, 1, 26),
    title: 'Uber',
    amount: '13,45',
    type: 'debit',
    category: 'transport',
  },
  {
    id: 9,
    date: new Date(2020, 1, 26),
    title: 'Poker Night',
    amount: '130,45',
    type: 'credit',
    category: 'fun',
  },
]
